AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  SystemId:
    Type: String
    Default: dify202508

  EnvId:
    Type: String
    Default: prod

  InstanceId:
    Description: EC2 Instance ID
    Type: String

  TargetGroupArn:
    Description: Target Group ARN
    Type: String

  StartTime:
    Description: Start time in cron format (UTC)
    Type: String
    Default: 'cron(0 0 ? * MON-FRI *)'

Resources:
  # EC2インスタンスを起動するためのLambda関数
  LambdaFunctionEC2InstanceStart:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "start-${SystemId}-${EnvId}-webapp-ec2-instance"
      Code:
        ZipFile: |
          import boto3
          import os
          
          def lambda_handler(event, context):
              instance_id = os.environ['INSTANCE_ID']
              target_group_arn = os.environ['TARGET_GROUP_ARN']
          
              ec2_client = boto3.client('ec2')
              elbv2_client = boto3.client('elbv2')
          
              response = ec2_client.describe_instances(InstanceIds=[instance_id])
              state = response['Reservations'][0]['Instances'][0]['State']['Name']
              print(f'Current state: {state}')
              
              if state == 'stopped':
                  ec2_client.start_instances(InstanceIds=[instance_id])
                  print('Started EC2 instance: {}'.format(instance_id))
                  
                  waiter = ec2_client.get_waiter('instance_running')
                  waiter.wait(InstanceIds=[instance_id])
                  print('EC2 instance is now running')
                  
                  try:
                      elbv2_client.register_targets(
                          TargetGroupArn=target_group_arn,
                          Targets=[{'Id': instance_id}]
                      )
                      print(f'Registered instance {instance_id} to target group')
                  except Exception as e:
                      print(f'Error registering target: {e}')
                  
                  return {
                      'statusCode': 200,
                      'body': 'Started EC2 instance successfully'
                  }
              else:
                  print('EC2 instance is already running')
                  return {
                      'statusCode': 200,
                      'body': 'EC2 instance is already running'
                  }
      Environment:
        Variables:
          INSTANCE_ID: !Ref InstanceId
          TARGET_GROUP_ARN: !Ref TargetGroupArn
      Handler: index.lambda_handler
      Role: {"Fn::ImportValue": !Sub "${SystemId}-${EnvId}-lambda-role-arn"}
      Runtime: python3.11
      Timeout: 300

  # AWS EventBridgeルール
  EventBridgeRuleEC2InstanceStart:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "start-${SystemId}-${EnvId}-webapp-ec2-instance"
      ScheduleExpression: !Ref StartTime
      Description: 'Start EC2 instances using EventBridge'
      Targets:
        - Id: 'FunctionEC2InstanceStart'
          Arn: !GetAtt LambdaFunctionEC2InstanceStart.Arn

  PermissionEventBridgeRuleEC2InstanceStart:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Sub "start-${SystemId}-${EnvId}-webapp-ec2-instance"
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt EventBridgeRuleEC2InstanceStart.Arn